import { StyleSheet } from 'react-native';

export const dashboardStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#00111D',
  },
  container: {
    flex: 1,
    backgroundColor: '#001018',
    paddingHorizontal: 12,
    paddingTop: 10,
  },
  fill: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  logoGroup: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  logoIcon: {
    width: 70,
    height: 70,
    marginRight: 2,
  },
  resortName: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '800',
    letterSpacing: 1,
    marginLeft: -2,
    marginTop: -2,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  headerIconButton: {
    backgroundColor: 'rgba(3, 31, 46, 0.58)',
    padding: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(51, 181, 255, 0.35)',
    shadowColor: '#00BFFF',
    shadowOpacity: 0.16,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  profileButton: {
    backgroundColor: 'rgba(51, 181, 255, 0.24)',
    padding: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.42)',
    shadowColor: '#00BFFF',
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  alertBox: {
  backgroundColor: '#9E0005',
  borderRadius: 18,
  paddingVertical: 14,
  paddingHorizontal: 16,
  marginBottom: 14,
  flexDirection: 'row',
  alignItems: 'center',
  borderWidth: 1,
  borderColor: 'rgba(255, 120, 120, 0.55)',
  shadowColor: '#FF2D2D',
  shadowOpacity: 0.25,
  shadowRadius: 14,
  shadowOffset: { width: 0, height: 8 },
  elevation: 8,
  },
  alertLabel: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '800',
  },
  alertTitle: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '900',
    marginTop: 5,
    lineHeight: 28,
  },
  alertDesc: {
    color: '#FFFFFF',
    fontSize: 12,
    marginTop: 4,
  },
  monitorCard: {
  backgroundColor: 'rgba(3, 31, 46, 0.58)',
  borderRadius: 18,
  overflow: 'hidden',
  borderWidth: 1,
  borderColor: 'rgba(51, 181, 255, 0.35)',
  marginBottom: 12,
  shadowColor: '#00BFFF',
  shadowOpacity: 0.16,
  shadowRadius: 16,
  shadowOffset: { width: 0, height: 8 },
  elevation: 8,
  },
  monitorTop: {
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  sectionTitle: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '900',
  },
  legendWrapper: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 9,
    marginTop: 10,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  legendDot: {
    width: 10,
    height: 10,
    borderRadius: 10,
  },
  legendText: {
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: '800',
  },
  mapContainer: {
    height: 360,
    position: 'relative',
    backgroundColor: '#00334A',
    overflow: 'hidden',
  },
  mapImage: {
    width: '100%',
    height: '100%',
  },
  marker: {
    position: 'absolute',
    alignItems: 'center',
    transform: [{ translateX: -15 }],
  },
  pulseRing: {
    position: 'absolute',
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 2,
    borderColor: '#B40012',
  },
  markerCircle: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 2,
    borderColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  totalBox: {
  position: 'absolute',
  left: 12,
  bottom: 12,
  backgroundColor: 'rgba(0, 17, 29, 0.72)',
  borderRadius: 12,
  padding: 9,
  width: 110,
  borderWidth: 1,
  borderColor: 'rgba(255, 255, 255, 0.14)',
  },
  totalLabel: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '900',
  },
  totalNumber: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '900',
    marginVertical: 1,
  },
  totalUpdated: {
    color: 'rgba(220, 240, 255, 0.68)',
    fontSize: 10,
  },
  statusBox: {
  backgroundColor: 'rgba(3, 31, 46, 0.58)',
  borderRadius: 18,
  borderWidth: 1,
  borderColor: 'rgba(51, 181, 255, 0.35)',
  paddingVertical: 13,
  paddingHorizontal: 14,
  marginBottom: 12,
  flexDirection: 'row',
  alignItems: 'center',
  shadowColor: '#00BFFF',
  shadowOpacity: 0.16,
  shadowRadius: 16,
  shadowOffset: { width: 0, height: 8 },
  elevation: 8,
  },
  statusTitle: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '900',
    width: 100,
  },
  divider: {
  width: 1,
  height: 40,
  backgroundColor: 'rgba(166, 220, 255, 0.24)',
  marginHorizontal: 10,
  },
  statusCount: {
    flex: 1,
    alignItems: 'center',
  },
  statusLabel: {
    fontSize: 11,
    fontWeight: '900',
  },
  statusNumber: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '900',
    marginTop: 4,
  },
  selectedCard: {
  backgroundColor: 'rgba(3, 31, 46, 0.58)',
  borderRadius: 18,
  borderWidth: 1,
  borderColor: 'rgba(51, 181, 255, 0.35)',
  padding: 14,
  marginBottom: 12,
  borderLeftWidth: 1,
  shadowColor: '#00BFFF',
  shadowOpacity: 0.16,
  shadowRadius: 16,
  shadowOffset: { width: 0, height: 8 },
  elevation: 8,
  },
  selectedCardDanger: {
    borderLeftWidth: 4,
    borderLeftColor: '#D00012',
  },
  selectedPlaceholderWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 18,
  },
  selectedPlaceholderIcon: {
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 2,
    borderColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
    opacity: 0.8,
  },
  selectedPlaceholderText: {
    color: '#FFFFFF',
    fontSize: 12,
    textAlign: 'center',
    lineHeight: 18,
    maxWidth: '90%',
  },
  selectedNameSection: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 10,
    marginBottom: 8,
  },
  guestNameLarge: {
    color: '#FFFFFF',
    fontSize: 28,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  badge: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '900',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
  },
  infoLine: {
  height: 1,
  backgroundColor: 'rgba(166, 220, 255, 0.24)',
  marginVertical: 14,
  },
  infoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  infoItem: {
    width: '33.33%',
    marginBottom: 14,
    paddingHorizontal: 6,
  },
  infoLabel: {
    color: 'rgba(220, 240, 255, 0.58)',
    fontSize: 10,
    fontWeight: '800',
  },
  infoValue: {
    color: '#FFFFFF',
    fontSize: 14,
    marginTop: 4,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'flex-end',
  },
  modalContent: {
  backgroundColor: 'rgba(0, 17, 29, 0.94)',
  borderTopLeftRadius: 24,
  borderTopRightRadius: 24,
  minHeight: '60%',
  paddingHorizontal: 16,
  paddingVertical: 20,
  borderWidth: 1,
  borderColor: 'rgba(51, 181, 255, 0.28)',
  },
  modalHeader: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  marginBottom: 20,
  paddingBottom: 16,
  borderBottomWidth: 1,
  borderBottomColor: 'rgba(51, 181, 255, 0.28)',
  },
  modalTitle: {
    color: '#FFFFFF',
    fontSize: 19,
    fontWeight: '900',
    letterSpacing: 1,
  },
  modalCloseButton: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: 'bold',
  },
  seeAllContainer: {
    alignSelf: 'flex-end',
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  seeAllText: {
    color: '#00CFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  modalEmptyState: {
    alignItems: 'flex-start',
    width: '100%',
    paddingHorizontal: 20,
  },
  notificationItem: {
  flexDirection: 'row',
  alignItems: 'center',
  backgroundColor: 'rgba(3, 31, 46, 0.58)',
  padding: 16,
  borderRadius: 16,
  marginBottom: 12,
  borderWidth: 1,
  borderColor: 'rgba(51, 181, 255, 0.28)',
  },
  notificationContent: {
    flex: 1,
    marginLeft: 12,
  },
  notificationMessage: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
  },
  notificationTime: {
    color: '#00CFFF',
    fontSize: 12,
    marginTop: 4,
  },
  profileModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.55)',
    alignItems: 'flex-end',
    paddingHorizontal: 12,
    paddingTop: 86,
  },
  profileModalContent: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: 'rgba(0, 17, 29, 0.96)',
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(51, 181, 255, 0.35)',
    shadowColor: '#00BFFF',
    shadowOpacity: 0.2,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  profileModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(51, 181, 255, 0.28)',
  },
  profileIdentity: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 18,
  },
  profileAvatar: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(51, 181, 255, 0.22)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.35)',
    marginRight: 12,
  },
  profileDetails: {
    flex: 1,
  },
  profileName: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '900',
  },
  accountInfoSection: {
    backgroundColor: 'rgba(3, 31, 46, 0.58)',
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: 'rgba(51, 181, 255, 0.28)',
    marginBottom: 18,
  },
  accountInfoTitle: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0.6,
    marginBottom: 12,
  },
  profileInfoRow: {
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: 'rgba(166, 220, 255, 0.18)',
  },
  profileInfoLabel: {
    color: 'rgba(220, 240, 255, 0.62)',
    fontSize: 11,
    fontWeight: '800',
  },
  profileInfoValue: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
    marginTop: 4,
  },
  changePasswordButton: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
    paddingVertical: 11,
    borderRadius: 12,
    backgroundColor: 'rgba(51, 181, 255, 0.16)',
    borderWidth: 1,
    borderColor: 'rgba(51, 181, 255, 0.38)',
  },
  changePasswordText: {
    color: '#00CFFF',
    fontSize: 13,
    fontWeight: '900',
  },
  profileLogoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#9E0005',
    borderRadius: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 120, 120, 0.55)',
  },
  profileLogoutText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
  },
});
